"""reporters/github_issue.py — format a benchmark report as a GitHub issue.

Reads results/<run-id>/report.md and run.json, produces a structured issue body
with: summary table, failing tasks, LLM-judged findings, and recommendations.

With --submit: opens the issue via GitHub API (requires issues:write scope).
"""
from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

RESULTS_DIR = Path(__file__).resolve().parents[1] / "results"

_ISSUE_TEMPLATE = """\
## Agent Health Report — {agent}

> **Automated benchmark report** generated by [agent-lab](https://github.com/{lab_repo}).
> Run ID: `{run_id}` · Battery: `{battery}` · Model: `{model}`

---

### Score Summary

{score_table}

---

### Failing / Marginal Tasks

{failing_section}

---

### Recommendations

{recommendations}

---

### Reproduce

```bash
lab fetch {source_repo}
lab bench {agent} --repo {source_repo}
```

<details>
<summary>Full report</summary>

{full_report}

</details>
"""


def _load_run(run_id: str) -> dict:
    path = RESULTS_DIR / run_id / "run.json"
    if not path.exists():
        raise FileNotFoundError(f"No run.json for '{run_id}'")
    return json.loads(path.read_text(encoding="utf-8"))


def _load_report_md(run_id: str) -> str:
    path = RESULTS_DIR / run_id / "report.md"
    if path.exists():
        return path.read_text(encoding="utf-8")
    return "*(report not yet generated — run `lab report <run-id>` first)*"


def _pct(total: int, max_score: int) -> int:
    return round(100 * total / max_score) if max_score else 0


def _build_score_table(tasks: list[dict]) -> str:
    rows = ["| Task | Score | % | Verdict |", "|---|---|---|---|"]
    for t in tasks:
        name = t.get("task", "?")
        status = t.get("status", "?")
        if status != "ok":
            rows.append(f"| {name} | — | — | ❌ {status} |")
            continue
        raw = t["scores"].get("total", 0)
        mx = t["scores"].get("max_score", 0)
        pct = _pct(raw, mx)
        verdict = "✅ Pass" if pct >= 80 else ("⚠️ Marginal" if pct >= 60 else "❌ Fail")
        rows.append(f"| {name} | {raw}/{mx} | {pct}% | {verdict} |")
    return "\n".join(rows)


def _build_failing_section(tasks: list[dict]) -> str:
    failing = [
        t for t in tasks
        if t.get("status") != "ok"
        or _pct(t["scores"].get("total", 0), t["scores"].get("max_score", 0)) < 80
    ]
    if not failing:
        return "All tasks passed at or above the 80% threshold. 🎉"

    parts: list[str] = []
    for t in failing:
        name = t.get("task", "?")
        if t.get("status") != "ok":
            parts.append(f"**{name}** — {t['status']}: {t.get('error', '')}")
            continue
        dims = t["scores"].get("dimensions", {})
        failed_dims = [d for d, v in dims.items() if v is False]
        pending_dims = [d for d, v in dims.items() if v is None]
        raw = t["scores"].get("total", 0)
        mx = t["scores"].get("max_score", 0)
        pct = _pct(raw, mx)
        lines = [f"**{name}** — {raw}/{mx} ({pct}%)"]
        if failed_dims:
            lines.append(f"  - Failed dimensions: {', '.join(f'`{d}`' for d in failed_dims)}")
        if pending_dims:
            lines.append(f"  - Pending (LLM judge): {', '.join(f'`{d}`' for d in pending_dims)}")
        parts.append("\n".join(lines))

    return "\n\n".join(parts)


def _build_recommendations(tasks: list[dict], agent: str) -> str:
    """Basic structural recommendations — EvalJudge fills in the qualitative ones."""
    recs: list[str] = []
    for t in tasks:
        if t.get("status") != "ok":
            continue
        dims = t["scores"].get("dimensions", {})
        task_name = t.get("task", "?")
        failed = [d for d, v in dims.items() if v is False]
        for d in failed:
            recs.append(f"- **{task_name}** / `{d}`: review agent instructions for this dimension")
    if not recs:
        return "No structural failures detected. Review LLM-judged dimensions via EvalJudge."
    recs.insert(0, "> ⚠️ These are structurally-derived recommendations. "
                   "EvalJudge will add qualitative analysis.\n")
    return "\n".join(recs)


def _submit_issue(repo: str, title: str, body: str) -> int:
    token = os.getenv("GITHUB_TOKEN", "")
    if not token:
        print("GITHUB_TOKEN not set — cannot submit issue.", file=sys.stderr)
        return 1

    url = f"https://api.github.com/repos/{repo}/issues"
    payload = json.dumps({"title": title, "body": body}).encode()
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())
        print(f"Issue created: {data.get('html_url')}")
        return 0
    except urllib.error.HTTPError as exc:
        print(f"GitHub API error {exc.code}: {exc.read().decode()}", file=sys.stderr)
        return 1


def generate_issue(run_id: str, *, submit: bool, repo: str | None) -> int:
    try:
        run = _load_run(run_id)
    except FileNotFoundError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    report_md = _load_report_md(run_id)
    agent = run.get("agent", "unknown")
    battery = run.get("battery", "unknown")
    model = run.get("model", "unknown")
    source_repo = run.get("source_repo") or repo or "unknown/unknown"
    tasks: list[dict] = run.get("tasks", [])

    issue_body = _ISSUE_TEMPLATE.format(
        agent=agent,
        lab_repo="agent-lab",   # placeholder — update when repo is public
        run_id=run_id,
        battery=battery,
        model=model,
        source_repo=source_repo,
        score_table=_build_score_table(tasks),
        failing_section=_build_failing_section(tasks),
        recommendations=_build_recommendations(tasks, agent),
        full_report=report_md,
    )

    issue_title = f"[agent-lab] Benchmark report — {agent} agent"

    # Always save locally
    issue_path = RESULTS_DIR / run_id / "issue.md"
    issue_path.write_text(issue_body, encoding="utf-8")
    print(f"Issue body saved: results/{run_id}/issue.md")

    if submit:
        target_repo = repo or source_repo
        if target_repo == "unknown/unknown":
            print("Specify --repo owner/repo to submit the issue.", file=sys.stderr)
            return 1
        print(f"Submitting issue to {target_repo}...")
        return _submit_issue(target_repo, issue_title, issue_body)

    print()
    print("To submit this issue:")
    print(f"  lab issue {run_id} --repo {source_repo} --submit")
    return 0
